# Generated by Django 5.2.7 on 2025-10-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_app', '0002_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/services/'),
        ),
    ]
