# Generated by Django 5.2.7 on 2025-10-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_app', '0003_alter_service_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='service_id',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Scheduled', max_length=10),
        ),
    ]
