# Generated by Django 5.2.7 on 2025-10-16 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_app', '0004_rename_service_id_booking_service_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='booking_id',
            new_name='booking',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='feedback',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
